name: Deploy master
on:
  push:
    branches:
    - cicd-setup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: |
        cd Ryder
        zip -r Ryder_backend.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        role-to-assume: ${{ secrets.MANAGED_INTERNSHIP_S3_ROLE }}
        application_name: Ryder-Backend
        environment_name: Ryder-Backend-env
        version_label: 1-2
        region: us-east-1
        deployment_package: Ryder_backend.zip